name          'element84-curl'
version       '0.0.1'
source        'https://github.com/Element84/puppet-curl'
author        'element84'
license       'Apache License, Version 2.0'
summary       'Installs curl'
description   'A simple module for installing curl'
project_page  'https://github.com/Element84/puppet-curl'

dependency 'puppetlabs/stdlib'
